### PR TITLE
Fixed wrong php version

### PR DESCRIPTION
**Pull request by Abbotton**
I run command `composer create-project larapie/larapie -vvv` on my MBP, But Composer throw exception:
```bash
[InvalidArgumentException]
  Could not find package larapie/larapie with stability stable in a version installable using your PHP version 7.1.23  .
```

So. I switch php version to v7.2, and it' worked!

### CODE REVIEW

**Comment by deviouspk** [comment]
Hey abbotton! Thanks for your pr. are you using the framework at the moment? If you do could you give some feedback?

**Comment by Abbotton** [comment]
@deviouspk Hi,deviouspk, I am trying to use larapie, and if there are any problems, I will give feedback in the first place.Thank you very much for creating the larapie project.

**Comment by anthonyvancauwenberghe** [comment]
It might be hard to dive into it without any documentation. If you have any questions i'll try to answer them asap

**Comment by Abbotton** [comment]
@deviouspk thank you very much

**Pull request merged**
